import Foundation
import SwiftUI

enum LocalizationManager {
    

    private static let translations: [String: [String: String]] = [
        "de": [
            "app_name": "SongFlip",
            "app_tagline": "Automatischer Musik-Link Redirector",
            "target_service_label": "Bevorzugter Ziel-Player",
            "nav_settings": "Einstellungen",
            "select_language_title": "Sprache wählen",
            "language_label": "Sprache",
            "theme_label": "Erscheinungsbild",
            "theme_dark": "Dunkel",
            "theme_light": "Hell",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Musik-Link einfügen (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Link umwandeln",
            "test_converting": "Löse Musik-Link auf...",
            "link_copied": "Link in Zwischenablage kopiert",
            "action_paste": "Aus Zwischenablage einfügen",
            "history_title": "Song-Verlauf",
            "history_empty": "Noch keine Songs im Verlauf. Sobald du Musik-Links teilst, erscheinen sie hier.",
            "history_clear_all": "Verlauf leeren",
            "history_clear_confirm_title": "Verlauf wirklich leeren?",
            "action_delete": "Löschen",
            "legal_privacy": "Datenschutz",
            "legal_imprint": "Impressum",
            "legal_terms": "Nutzungsbedingungen",
            "redirect_error_toast": "Link konnte nicht umgewandelt werden. Original-Link wird geöffnet."
        ],
        "en": [
            "app_name": "SongFlip",
            "app_tagline": "Automatic Music Link Redirector",
            "target_service_label": "Preferred Target Player",
            "nav_settings": "Settings",
            "select_language_title": "Select Language",
            "language_label": "Language",
            "theme_label": "Theme",
            "theme_dark": "Dark",
            "theme_light": "Light",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Paste music link (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convert Link",
            "test_converting": "Resolving music link...",
            "link_copied": "Link copied to clipboard",
            "action_paste": "Paste from Clipboard",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Privacy Policy",
            "legal_imprint": "Imprint",
            "legal_terms": "Terms of Service",
            "redirect_error_toast": "Could not flip link. Opening original link."
        ],
        "da": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musik-link-omdirigering",
            "target_service_label": "Foretrukken mål-afspiller",
            "nav_settings": "Indstillinger",
            "select_language_title": "Vælg sprog",
            "language_label": "Sprog",
            "theme_label": "Tema",
            "theme_dark": "Mørkt",
            "theme_light": "Lyst",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Indsæt musiklink (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konverter link",
            "test_converting": "Omdirigerer via Odesli API...",
            "link_copied": "Link kopieret til udklipsholder",
            "action_paste": "Indsæt fra udklipsholder",
            "history_title": "Sanghistorik",
            "history_empty": "Ingen konverterede sange endnu. Delte musiklinks vises her.",
            "history_clear_all": "Ryd historik",
            "history_clear_confirm_title": "Vil du rydde sanghistorikken?",
            "action_delete": "Slet",
            "legal_privacy": "Privatliv",
            "legal_imprint": "Kolofon",
            "legal_terms": "Brugsvilkår",
            "redirect_error_toast": "Kunne ikke omdirigere link. Åbner oprindeligt link."
        ],
        "nb": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musikklenke-omdirigering",
            "target_service_label": "Foretrukket målspiller",
            "nav_settings": "Innstillinger",
            "select_language_title": "Velg språk",
            "language_label": "Språk",
            "theme_label": "Tema",
            "theme_dark": "Mørkt",
            "theme_light": "Lyst",
            "theme_system": "System",
            "nav_test_studio": "Teststudio",
            "test_placeholder": "Lim inn musikklenke (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konverter lenke",
            "test_converting": "Omdirigerer via Odesli API...",
            "link_copied": "Lenke kopiert til utklippstavlen",
            "action_paste": "Lim inn fra utklippstavlen",
            "history_title": "Sanghistorikk",
            "history_empty": "Ingen konverterte sanger ennå. Delte musikklenker vises her.",
            "history_clear_all": "Tøm historikk",
            "history_clear_confirm_title": "Tømme sanghistorikken?",
            "action_delete": "Slett",
            "legal_privacy": "Personvern",
            "legal_imprint": "Kolofon",
            "legal_terms": "Vilkår for bruk",
            "redirect_error_toast": "Kunne ikke omdirigere lenke. Åpner originallenke."
        ],
        "sv": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musiklänks-omdirigering",
            "target_service_label": "Föredragen målspelare",
            "nav_settings": "Inställningar",
            "select_language_title": "Välj språk",
            "language_label": "Språk",
            "theme_label": "Tema",
            "theme_dark": "Mörkt",
            "theme_light": "Ljust",
            "theme_system": "System",
            "nav_test_studio": "Teststudio",
            "test_placeholder": "Klistra in musiklänk (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konvertera länk",
            "test_converting": "Omdirigerar via Odesli API...",
            "link_copied": "Länk kopierad till urklipp",
            "action_paste": "Klistra in från urklipp",
            "history_title": "Låthistorik",
            "history_empty": "Inga konverterade låtar än. Delade musiklänkar visas här.",
            "history_clear_all": "Rensa historik",
            "history_clear_confirm_title": "Rensa låthistorik?",
            "action_delete": "Radera",
            "legal_privacy": "Integritet",
            "legal_imprint": "Kolofon",
            "legal_terms": "Användarvillkor",
            "redirect_error_toast": "Kunde inte omdirigera länk. Öppnar originallänk."
        ],
        "nl": [
            "app_name": "SongFlip",
            "app_tagline": "Automatische muzieklink-omleiding",
            "target_service_label": "Voorkeurs-doelspeler",
            "nav_settings": "Instellingen",
            "select_language_title": "Selecteer taal",
            "language_label": "Taal",
            "theme_label": "Thema",
            "theme_dark": "Donker",
            "theme_light": "Licht",
            "theme_system": "Systeem",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Plak muzieklink (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Link omzetten",
            "test_converting": "Omzetten via Odesli API...",
            "link_copied": "Link gekopieerd naar klembord",
            "action_paste": "Plakken vanaf klembord",
            "history_title": "Nummergeschiedenis",
            "history_empty": "Nog geen geconverteerde nummers. Gedeelde muzieklinks verschijnen hier.",
            "history_clear_all": "Geschiedenis wissen",
            "history_clear_confirm_title": "Geschiedenis wissen?",
            "action_delete": "Verwijderen",
            "legal_privacy": "Privacy",
            "legal_imprint": "Colofon",
            "legal_terms": "Gebruiksvoorwaarden",
            "redirect_error_toast": "Kon link niet omleiden. Oorspronkelijke link wordt geopend."
        ],
        "fr": [
            "app_name": "SongFlip",
            "app_tagline": "Redirection automatique de liens musicaux",
            "target_service_label": "Lecteur cible préféré",
            "nav_settings": "Paramètres",
            "select_language_title": "Choisir la langue",
            "language_label": "Langue",
            "theme_label": "Thème",
            "theme_dark": "Sombre",
            "theme_light": "Clair",
            "theme_system": "Système",
            "nav_test_studio": "Studio de test",
            "test_placeholder": "Collez un lien musical (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convertir le lien",
            "test_converting": "Résolution via l'API Odesli...",
            "link_copied": "Lien copié dans le presse-papiers",
            "action_paste": "Coller depuis le presse-papiers",
            "history_title": "Historique des morceaux",
            "history_empty": "Aucun morceau converti. Les liens partagés apparaîtront ici.",
            "history_clear_all": "Effacer l'historique",
            "history_clear_confirm_title": "Effacer l'historique ?",
            "action_delete": "Supprimer",
            "legal_privacy": "Confidentialité",
            "legal_imprint": "Mentions légales",
            "legal_terms": "\"Conditions d'utilisation\"",
            "redirect_error_toast": "Impossible de rediriger le lien. Ouverture du lien d'origine."
        ],
        "es": [
            "app_name": "SongFlip",
            "app_tagline": "Redirección automática de enlaces de música",
            "target_service_label": "Reproductor de destino preferido",
            "nav_settings": "Ajustes",
            "select_language_title": "Seleccionar idioma",
            "language_label": "Idioma",
            "theme_label": "Tema",
            "theme_dark": "Oscuro",
            "theme_light": "Claro",
            "theme_system": "Sistema",
            "nav_test_studio": "Estudio de prueba",
            "test_placeholder": "Pega un enlace de música (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convertir enlace",
            "test_converting": "Resolviendo mediante la API de Odesli...",
            "link_copied": "Enlace copiado al portapapeles",
            "action_paste": "Pegar desde el portapapeles",
            "history_title": "Historial de canciones",
            "history_empty": "Aún no hay canciones convertidas. Los enlaces compartidos aparecerán aquí.",
            "history_clear_all": "Borrar historial",
            "history_clear_confirm_title": "¿Borrar historial?",
            "action_delete": "Eliminar",
            "legal_privacy": "Privacidad",
            "legal_imprint": "Aviso legal",
            "legal_terms": "Términos de servicio",
            "redirect_error_toast": "No se pudo redirigir el enlace. Abriendo enlace original."
        ],
        "it": [
            "app_name": "SongFlip",
            "app_tagline": "Reindirizzamento automatico dei link musicali",
            "target_service_label": "Lettore di destinazione preferito",
            "nav_settings": "Impostazioni",
            "select_language_title": "Seleziona lingua",
            "language_label": "Lingua",
            "theme_label": "Tema",
            "theme_dark": "Scuro",
            "theme_light": "Chiaro",
            "theme_system": "Sistema",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Incolla link musicale (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Converti link",
            "test_converting": "Risoluzione tramite API Odesli...",
            "link_copied": "Link copiato negli appunti",
            "action_paste": "Incolla dagli appunti",
            "history_title": "Cronologia brani",
            "history_empty": "Nessun brano convertito. I link musicali condivisi appariranno qui.",
            "history_clear_all": "Cancella cronologia",
            "history_clear_confirm_title": "Cancellare la cronologia?",
            "action_delete": "Elimina",
            "legal_privacy": "Privacy",
            "legal_imprint": "Informazioni legali",
            "legal_terms": "Termini di servizio",
            "redirect_error_toast": "Impossibile reindirizzare il link. Apertura del link originale."
        ],
        "pt": [
            "app_name": "SongFlip",
            "app_tagline": "Redirecionamento automático de links de música",
            "target_service_label": "Reprodutor de destino preferido",
            "nav_settings": "Configurações",
            "select_language_title": "Selecionar idioma",
            "language_label": "Idioma",
            "theme_label": "Tema",
            "theme_dark": "Escuro",
            "theme_light": "Claro",
            "theme_system": "Sistema",
            "nav_test_studio": "Estúdio de Teste",
            "test_placeholder": "Cole o link de música (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Converter link",
            "test_converting": "A resolver via API Odesli...",
            "link_copied": "Link copiado para a área de transferência",
            "action_paste": "Colar da área de transferência",
            "history_title": "Histórico de Músicas",
            "history_empty": "Nenhuma música convertida ainda. Links de música compartilhados aparecerão aqui.",
            "history_clear_all": "Limpar Histórico",
            "history_clear_confirm_title": "Limpar histórico de músicas?",
            "action_delete": "Excluir",
            "legal_privacy": "Privacidade",
            "legal_imprint": "Aviso legal",
            "legal_terms": "Termos de serviço",
            "redirect_error_toast": "Não foi possível redirecionar o link. A abrir link original."
        ],
        "pl": [
            "app_name": "SongFlip",
            "app_tagline": "Automatyczne przekierowywanie linków muzycznych",
            "target_service_label": "Preferowany odtwarzacz docelowy",
            "nav_settings": "Ustawienia",
            "select_language_title": "Wybierz język",
            "language_label": "Język",
            "theme_label": "Motyw",
            "theme_dark": "Ciemny",
            "theme_light": "Jasny",
            "theme_system": "System",
            "nav_test_studio": "Studio testowe",
            "test_placeholder": "Wklej link muzyczny (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konwertuj link",
            "test_converting": "Rozwiązywanie przez Odesli API...",
            "link_copied": "Link skopiowany do schowka",
            "action_paste": "Wklej ze schowka",
            "history_title": "Historia utworów",
            "history_empty": "Brak przekonwertowanych utworów. Udostępnione linki pojawią się tutaj.",
            "history_clear_all": "Wyczyść historię",
            "history_clear_confirm_title": "Wyczyścić historię?",
            "action_delete": "Usuń",
            "legal_privacy": "Prywatność",
            "legal_imprint": "Nota prawna",
            "legal_terms": "Regulamin",
            "redirect_error_toast": "Nie udało się przekierować linku. Otwieranie oryginalnego linku."
        ],
        "ru": [
            "app_name": "SongFlip",
            "app_tagline": "Автоматическая переадресация музыкальных ссылок",
            "target_service_label": "Предпочитаемый плеер",
            "nav_settings": "Настройки",
            "select_language_title": "Выберите язык",
            "language_label": "Язык",
            "theme_label": "Тема",
            "theme_dark": "Тёмная",
            "theme_light": "Светлая",
            "theme_system": "Система",
            "nav_test_studio": "Тестовая студия",
            "test_placeholder": "Вставьте ссылку (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Преобразовать ссылку",
            "test_converting": "Обработка через Odesli API...",
            "link_copied": "Ссылка скопирована в буфер обмена",
            "action_paste": "Вставить из буфера",
            "history_title": "История треков",
            "history_empty": "Пока нет сконвертированных треков. Ссылки появятся здесь.",
            "history_clear_all": "Очистить историю",
            "history_clear_confirm_title": "Очистить историю треков?",
            "action_delete": "Удалить",
            "legal_privacy": "Конфиденциальность",
            "legal_imprint": "Выходные данные",
            "legal_terms": "Условия использования",
            "redirect_error_toast": "Не удалось перенаправить ссылку. Открываем оригинал."
        ],
        "tr": [
            "app_name": "SongFlip",
            "app_tagline": "Otomatik Müzik Bağlantısı Yönlendirici",
            "target_service_label": "Tercih Edilen Hedef Oynatıcı",
            "nav_settings": "Ayarlar",
            "select_language_title": "Dil Seçin",
            "language_label": "Dil",
            "theme_label": "Tema",
            "theme_dark": "Koyu",
            "theme_light": "Açık",
            "theme_system": "Sistem",
            "nav_test_studio": "Test Stüdyosu",
            "test_placeholder": "Müzik bağlantısını yapıştırın (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Bağlantıyı Dönüştür",
            "test_converting": "Odesli API ile çözülüyor...",
            "link_copied": "Bağlantı panoya kopyalandı",
            "action_paste": "Panodan Yapıştır",
            "history_title": "Şarkı Geçmişi",
            "history_empty": "Henüz dönüştürülmüş şarkı yok. Paylaşılan müzik bağlantıları burada görünecektir.",
            "history_clear_all": "Geçmişi Temizle",
            "history_clear_confirm_title": "Şarkı geçmişi temizlensin mi?",
            "action_delete": "Sil",
            "legal_privacy": "Gizlilik",
            "legal_imprint": "Künye",
            "legal_terms": "Hizmet Şartları",
            "redirect_error_toast": "Bağlantı yönlendirilemedi. Orijinal bağlantı açılıyor."
        ],
        "uk": [
            "app_name": "SongFlip",
            "app_tagline": "Автоматична переадресація музичних посилань",
            "target_service_label": "Бажаний цільовий плеєр",
            "nav_settings": "Налаштування",
            "select_language_title": "Оберіть мову",
            "language_label": "Мова",
            "theme_label": "Тема",
            "theme_dark": "Темна",
            "theme_light": "Світла",
            "theme_system": "Система",
            "nav_test_studio": "Тестова студія",
            "test_placeholder": "Вставте посилання (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Перетворити посилання",
            "test_converting": "Обробка через Odesli API...",
            "link_copied": "Посилання скопійовано в буфер обміну",
            "action_paste": "Вставити з буфера",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Конфіденційність",
            "legal_imprint": "Вихідні дані",
            "legal_terms": "Умови використання",
            "redirect_error_toast": "Не вдалося перенаправити посилання. Відкриваємо оригінал."
        ],
        "ja": [
            "app_name": "SongFlip",
            "app_tagline": "音楽リンク自動リダイレクター",
            "target_service_label": "優先ターゲットプレーヤー",
            "nav_settings": "設定",
            "select_language_title": "言語を選択",
            "language_label": "言語",
            "theme_label": "テーマ",
            "theme_dark": "ダーク",
            "theme_light": "ライト",
            "theme_system": "システム",
            "nav_test_studio": "テストスタジオ",
            "test_placeholder": "音楽リンクを貼り付け (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "リンクを変換",
            "test_converting": "Odesli API で解決中...",
            "link_copied": "クリップボードにコピーしました",
            "action_paste": "クリップボードから貼り付け",
            "history_title": "楽曲履歴",
            "history_empty": "変換された楽曲はまだありません。共有されたリンクがここに表示されます。",
            "history_clear_all": "履歴を消去",
            "history_clear_confirm_title": "楽曲履歴を消去しますか？",
            "action_delete": "削除",
            "legal_privacy": "プライバシー",
            "legal_imprint": "法的情報",
            "legal_terms": "利用規約",
            "redirect_error_toast": "リンクをリダイレクトできませんでした。元のリンクを開きます。"
        ],
        "ko": [
            "app_name": "SongFlip",
            "app_tagline": "음악 링크 자동 리디렉터",
            "target_service_label": "선호하는 대상 플레이어",
            "nav_settings": "설정",
            "select_language_title": "언어 선택",
            "language_label": "언어",
            "theme_label": "테마",
            "theme_dark": "다크",
            "theme_light": "라이트",
            "theme_system": "시스템",
            "nav_test_studio": "테스트 스튜디오",
            "test_placeholder": "음악 링크 붙여넣기 (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "링크 변환",
            "test_converting": "Odesli API를 통해 확인 중...",
            "link_copied": "클립보드에 링크가 복사되었습니다",
            "action_paste": "클립보드에서 붙여넣기",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "개인정보처리방침",
            "legal_imprint": "법적 고지",
            "legal_terms": "이용약관",
            "redirect_error_toast": "링크를 리디렉션할 수 없습니다. 원본 링크를 엽니다."
        ],
        "zh": [
            "app_name": "SongFlip",
            "app_tagline": "音乐链接自动重定向器",
            "target_service_label": "首选目标播放器",
            "nav_settings": "设置",
            "select_language_title": "选择语言",
            "language_label": "语言",
            "theme_label": "主题",
            "theme_dark": "深色",
            "theme_light": "浅色",
            "theme_system": "系统",
            "nav_test_studio": "测试工作室",
            "test_placeholder": "粘贴音乐链接 (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "转换链接",
            "test_converting": "通过 Odesli API 解析中...",
            "link_copied": "链接已复制到剪贴板",
            "action_paste": "从剪贴板粘贴",
            "history_title": "歌曲历史",
            "history_empty": "暂无转换记录。分享的音乐链接将显示在这里。",
            "history_clear_all": "清除历史记录",
            "history_clear_confirm_title": "确定清除歌曲历史？",
            "action_delete": "删除",
            "legal_privacy": "隐私政策",
            "legal_imprint": "版本说明",
            "legal_terms": "服务条款",
            "redirect_error_toast": "无法重定向链接。正在打开原始链接。"
        ],
        "in": [
            "app_name": "SongFlip",
            "app_tagline": "Pengalihan Tautan Musik Otomatis",
            "target_service_label": "Pemutar Tujuan Favorit",
            "nav_settings": "Pengaturan",
            "select_language_title": "Pilih Bahasa",
            "language_label": "Bahasa",
            "theme_label": "Tema",
            "theme_dark": "Gelap",
            "theme_light": "Terang",
            "theme_system": "Sistem",
            "nav_test_studio": "Studio Uji",
            "test_placeholder": "Tempel tautan musik (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konversi Tautan",
            "test_converting": "Menyelesaikan melalui Odesli API...",
            "link_copied": "Tautan disalin ke papan klip",
            "action_paste": "Tempel dari Papan Klip",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Privasi",
            "legal_imprint": "Impresum",
            "legal_terms": "Ketentuan Layanan",
            "redirect_error_toast": "Gagal mengalihkan tautan. Membuka tautan asli."
        ],
        "vi": [
            "app_name": "SongFlip",
            "app_tagline": "Tự động chuyển hướng liên kết âm nhạc",
            "target_service_label": "Trình phát mục tiêu ưa thích",
            "nav_settings": "Cài đặt",
            "select_language_title": "Chọn ngôn ngữ",
            "language_label": "Ngôn ngữ",
            "theme_label": "Giao diện",
            "theme_dark": "Tối",
            "theme_light": "Sáng",
            "theme_system": "Hệ thống",
            "nav_test_studio": "Phòng thử nghiệm",
            "test_placeholder": "Dán liên kết âm nhạc (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Chuyển đổi liên kết",
            "test_converting": "Đang phân giải qua Odesli API...",
            "link_copied": "Đã sao chép liên kết vào khay nhớ tạm",
            "action_paste": "Dán từ khay nhớ tạm",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Bảo mật",
            "legal_imprint": "Thông tin pháp lý",
            "legal_terms": "Điều khoản dịch vụ",
            "redirect_error_toast": "Không thể chuyển hướng liên kết. Đang mở liên kết gốc."
        ],
        "bn": [
            "app_name": "SongFlip",
            "app_tagline": "স্বয়ংক্রিয় মিউজিক লিঙ্ক রিডাইরেক্টর",
            "target_service_label": "পছন্দের লক্ষ্য প্লেয়ার",
            "nav_settings": "সেটিংস",
            "select_language_title": "ভাষা নির্বাচন করুন",
            "language_label": "ভাষা",
            "theme_label": "থিম",
            "theme_dark": "গাঢ়",
            "theme_light": "হালকা",
            "theme_system": "সিস্টেম",
            "nav_test_studio": "টেস্ট স্টুডিও",
            "test_placeholder": "মিউজিক লিঙ্ক পেস্ট করুন (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "লিঙ্ক রূপান্তর করুন",
            "test_converting": "Odesli API এর মাধ্যমে সমাধান করা হচ্ছে...",
            "link_copied": "লিঙ্ক ক্লিপবোর্ডে কপি করা হয়েছে",
            "action_paste": "ক্লিপবোর্ড থেকে পেস্ট করুন",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "গোপনীয়তা",
            "legal_imprint": "আইনি বিজ্ঞপ্তি",
            "legal_terms": "পরিষেবার শর্তাবলী",
            "redirect_error_toast": "লিঙ্ক রিডাইরেক্ট করা যায়নি। আসল লিঙ্ক খোলা হচ্ছে।"
        ],
        "hi": [
            "app_name": "SongFlip",
            "app_tagline": "स्वचालित संगीत लिंक रीडायरेक्टर",
            "target_service_label": "पसंदीदा लक्ष्य प्लेयर",
            "nav_settings": "सेटिंग्स",
            "select_language_title": "भाषा चुनें",
            "language_label": "भाषा",
            "theme_label": "थीम",
            "theme_dark": "डार्क",
            "theme_light": "लाइट",
            "theme_system": "सिस्टम",
            "nav_test_studio": "टेस्ट स्टूडियो",
            "test_placeholder": "संगीत लिंक पेस्ट करें (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "लिंक बदलें",
            "test_converting": "Odesli API के माध्यम से समाधान हो रहा है...",
            "link_copied": "लिंक क्लिपबोर्ड पर कॉपी किया गया",
            "action_paste": "क्लिपबोर्ड से पेस्ट करें",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "गोपनीयता",
            "legal_imprint": "कानूनी नोटिस",
            "legal_terms": "सेवा की शर्तें",
            "redirect_error_toast": "लिंक रीडायरेक्ट नहीं किया जा सका। मूल लिंक खोला जा रहा है।"
        ],
        "mr": [
            "app_name": "SongFlip",
            "app_tagline": "स्वयंचलित संगीत लिंक पुनर्निर्देशन",
            "target_service_label": "पसंतीचा टार्गेट प्लेअर",
            "nav_settings": "सेटिंग्ज",
            "select_language_title": "भाषा निवडा",
            "language_label": "भाषा",
            "theme_label": "थीम",
            "theme_dark": "डार्क",
            "theme_light": "लाइट",
            "theme_system": "सिस्टम",
            "nav_test_studio": "चाचणी स्टुडिओ",
            "test_placeholder": "संगीत लिंक पेस्ट करा (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "लिंक बदला",
            "test_converting": "Odesli API द्वारे शोधत आहे...",
            "link_copied": "लिंक क्लिपबोर्डवर कॉपी केली",
            "action_paste": "क्लिपबोर्डवरून पेस्ट करा",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "गोपनीयता",
            "legal_imprint": "कायदेशीर सूचना",
            "legal_terms": "सेवा अटी",
            "redirect_error_toast": "लिंक पुनर्निर्देशित करता आली नाही. मूळ लिंक उघडत आहे."
        ]
    ]

    static func string(for key: String, lang: String) -> String {
        if let dict = translations[lang], let val = dict[key] {
            return val
        }
        if let enDict = translations["en"], let val = enDict[key] {
            return val
        }
        return key
    }
}

extension View {
    func localized(_ key: String, lang: String) -> String {
        LocalizationManager.string(for: key, lang: lang)
    }
}
