import Foundation
import SwiftUI

enum LocalizationManager {
    private static let translations: [String: [String: String]] = [
        "de": [
            "app_name": "SongFlip",
            "app_tagline": "Automatischer Musik-Link Redirector",
            "target_service_label": "Bevorzugter Ziel-Player",
            "nav_settings": "Einstellungen",
            "select_language_title": "Sprache wählen",
            "language_label": "Sprache",
            "theme_label": "Erscheinungsbild",
            "theme_dark": "Dunkel",
            "theme_light": "Hell",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Musik-Link einfügen (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Link umwandeln",
            "test_converting": "Löse Musik-Link auf...",
            "link_copied": "Link in Zwischenablage kopiert",
            "action_paste": "Aus Zwischenablage einfügen",
            "history_title": "Song-Verlauf",
            "history_empty": "Noch keine Songs im Verlauf. Sobald du Musik-Links teilst, erscheinen sie hier.",
            "history_clear_all": "Verlauf leeren",
            "history_clear_confirm_title": "Verlauf wirklich leeren?",
            "action_delete": "Löschen",
            "legal_privacy": "Datenschutz",
            "legal_imprint": "Impressum",
            "legal_terms": "Nutzungsbedingungen",
            "redirect_error_toast": "Link konnte nicht umgewandelt werden. Original-Link wird geöffnet.",
            "section_general": "ALLGEMEIN",
            "btn_done": "Fertig",
            "btn_close": "Schließen",
            "btn_cancel": "Abbrechen",
            "auto_clipboard": "Zwischenablage automatisch scannen",
            "one_tap_selection": "1-Tap Auswahl",
            "how_it_works_ios": "WIE FUNKTIONIERT ES UNTER IOS?",
            "step1_title": "1. Über das Teilen-Menü",
            "step1_desc": "Tippe in Spotify, Apple Music oder YouTube auf Teilen ➔ SongFlip für den sofortigen Sprung.",
            "step2_title": "2. Action Button & Kurzbefehle",
            "step2_desc": "Lege den SongFlip Kurzbefehl auf deinen Action Button für 1-Klick Konvertierung.",
            "step3_title": "3. Automatische Zwischenablage",
            "step3_desc": "Kopierte Musik-Links werden beim Öffnen der App automatisch erkannt.",
            "recent_songs": "LETZTE SONGS",
            "show_all": "Alle anzeigen",
            "clipboard_pasted": "Link aus Zwischenablage eingefügt!",
            "clipboard_detected": "Link aus Zwischenablage erkannt!",
            "history_empty_title": "Noch kein Verlauf",
            "unknown_song": "Unbekannter Song"
        ],
        "en": [
            "app_name": "SongFlip",
            "app_tagline": "Automatic Music Link Redirector",
            "target_service_label": "Preferred Target Player",
            "nav_settings": "Settings",
            "select_language_title": "Select Language",
            "language_label": "Language",
            "theme_label": "Theme",
            "theme_dark": "Dark",
            "theme_light": "Light",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Paste music link (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convert Link",
            "test_converting": "Resolving music link...",
            "link_copied": "Link copied to clipboard",
            "action_paste": "Paste from Clipboard",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Privacy Policy",
            "legal_imprint": "Imprint",
            "legal_terms": "Terms of Service",
            "redirect_error_toast": "Could not flip link. Opening original link.",
            "section_general": "GENERAL",
            "btn_done": "Done",
            "btn_close": "Close",
            "btn_cancel": "Cancel",
            "auto_clipboard": "Auto-detect clipboard",
            "one_tap_selection": "1-Tap Selection",
            "how_it_works_ios": "HOW DOES IT WORK ON IOS?",
            "step1_title": "1. Via Share Menu",
            "step1_desc": "Tap Share in Spotify, Apple Music or YouTube ➔ SongFlip for instant playback.",
            "step2_title": "2. Action Button & Shortcuts",
            "step2_desc": "Assign the SongFlip Shortcut to your Action Button for 1-click conversion.",
            "step3_title": "3. Automatic Clipboard",
            "step3_desc": "Copied music links are automatically detected when opening the app.",
            "recent_songs": "RECENT SONGS",
            "show_all": "Show all",
            "clipboard_pasted": "Link pasted from clipboard!",
            "clipboard_detected": "Link detected from clipboard!",
            "history_empty_title": "No history yet",
            "unknown_song": "Unknown Song"
        ],
        "da": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musik-link-omdirigering",
            "target_service_label": "Foretrukken mål-afspiller",
            "nav_settings": "Indstillinger",
            "select_language_title": "Vælg sprog",
            "language_label": "Sprog",
            "theme_label": "Tema",
            "theme_dark": "Mørkt",
            "theme_light": "Lyst",
            "theme_system": "System",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Indsæt musiklink (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konverter link",
            "test_converting": "Omdirigerer via Odesli API...",
            "link_copied": "Link kopieret til udklipsholder",
            "action_paste": "Indsæt fra udklipsholder",
            "history_title": "Sanghistorik",
            "history_empty": "Ingen konverterede sange endnu. Delte musiklinks vises her.",
            "history_clear_all": "Ryd historik",
            "history_clear_confirm_title": "Vil du rydde sanghistorikken?",
            "action_delete": "Slet",
            "legal_privacy": "Privatliv",
            "legal_imprint": "Kolofon",
            "legal_terms": "Brugsvilkår",
            "redirect_error_toast": "Kunne ikke omdirigere link. Åbner oprindeligt link.",
            "section_general": "GENERELT",
            "btn_done": "Færdig",
            "btn_close": "Luk",
            "btn_cancel": "Annuller",
            "auto_clipboard": "Scan udklipsholder automatisk",
            "one_tap_selection": "1-Tryk valg",
            "how_it_works_ios": "HVORDAN VIRKER DET PÅ IOS?",
            "step1_title": "1. Via delemenuen",
            "step1_desc": "Tryk på Del i Spotify, Apple Music eller YouTube ➔ SongFlip for øjeblikkelig afspilning.",
            "step2_title": "2. Handlingsknap & Genveje",
            "step2_desc": "Tilknyt SongFlip-genvejen til din handlingsknap for 1-kliks konvertering.",
            "step3_title": "3. Automatisk udklipsholder",
            "step3_desc": "Kopierede musiklinks registreres automatisk, når appen åbnes.",
            "recent_songs": "SENESTE SANGE",
            "show_all": "Vis alle",
            "clipboard_pasted": "Link indsat fra udklipsholder!",
            "clipboard_detected": "Link registreret i udklipsholder!",
            "history_empty_title": "Ingen historik endnu",
            "unknown_song": "Ukendt sang"
        ],
        "nb": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musikklenke-omdirigering",
            "target_service_label": "Foretrukket målspiller",
            "nav_settings": "Innstillinger",
            "select_language_title": "Velg språk",
            "language_label": "Språk",
            "theme_label": "Tema",
            "theme_dark": "Mørkt",
            "theme_light": "Lyst",
            "theme_system": "System",
            "nav_test_studio": "Teststudio",
            "test_placeholder": "Lim inn musikklenke (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konverter lenke",
            "test_converting": "Omdirigerer via Odesli API...",
            "link_copied": "Lenke kopiert til utklippstavlen",
            "action_paste": "Lim inn fra utklippstavlen",
            "history_title": "Sanghistorikk",
            "history_empty": "Ingen konverterte sanger ennå. Delte musikklenker vises her.",
            "history_clear_all": "Tøm historikk",
            "history_clear_confirm_title": "Tømme sanghistorikken?",
            "action_delete": "Slett",
            "legal_privacy": "Personvern",
            "legal_imprint": "Kolofon",
            "legal_terms": "Vilkår for bruk",
            "redirect_error_toast": "Kunne ikke omdirigere lenke. Åpner originallenke.",
            "section_general": "GENERELT",
            "btn_done": "Ferdig",
            "btn_close": "Lukk",
            "btn_cancel": "Avbryt",
            "auto_clipboard": "Skann utklippstavle automatisk",
            "one_tap_selection": "1-Trykks valg",
            "how_it_works_ios": "HVORDAN FUNGERER DET PÅ IOS?",
            "step1_title": "1. Via delemenyen",
            "step1_desc": "Trykk Del i Spotify, Apple Music eller YouTube ➔ SongFlip for direkte avspilling.",
            "step2_title": "2. Handlingsknapp & Snarveier",
            "step2_desc": "Legg SongFlip-snarveien til handlingsknappen for 1-klikks konvertering.",
            "step3_title": "3. Automatisk utklippstavle",
            "step3_desc": "Kopierte musikklenker oppdages automatisk når appen åpnes.",
            "recent_songs": "NYLIGE SANGER",
            "show_all": "Vis alle",
            "clipboard_pasted": "Lenke limt inn fra utklippstavlen!",
            "clipboard_detected": "Lenke funnet på utklippstavlen!",
            "history_empty_title": "Ingen historikk ennå",
            "unknown_song": "Ukjent sang"
        ],
        "sv": [
            "app_name": "SongFlip",
            "app_tagline": "Automatisk musiklänks-omdirigering",
            "target_service_label": "Föredragen målspelare",
            "nav_settings": "Inställningar",
            "select_language_title": "Välj språk",
            "language_label": "Språk",
            "theme_label": "Tema",
            "theme_dark": "Mörkt",
            "theme_light": "Ljust",
            "theme_system": "System",
            "nav_test_studio": "Teststudio",
            "test_placeholder": "Klistra in musiklänk (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konvertera länk",
            "test_converting": "Omdirigerar via Odesli API...",
            "link_copied": "Länk kopierad till urklipp",
            "action_paste": "Klistra in från urklipp",
            "history_title": "Låthistorik",
            "history_empty": "Inga konverterade låtar än. Delade musiklänkar visas här.",
            "history_clear_all": "Rensa historik",
            "history_clear_confirm_title": "Rensa låthistorik?",
            "action_delete": "Radera",
            "legal_privacy": "Integritet",
            "legal_imprint": "Kolofon",
            "legal_terms": "Användarvillkor",
            "redirect_error_toast": "Kunde inte omdirigera länk. Öppnar originallänk.",
            "section_general": "ALLMÄNT",
            "btn_done": "Klar",
            "btn_close": "Stäng",
            "btn_cancel": "Avbryt",
            "auto_clipboard": "Läs urklipp automatiskt",
            "one_tap_selection": "1-Trycksval",
            "how_it_works_ios": "HUR FUNGERAR DET PÅ IOS?",
            "step1_title": "1. Via delningsmenyn",
            "step1_desc": "Tryck på Dela i Spotify, Apple Music eller YouTube ➔ SongFlip för att spela direkt.",
            "step2_title": "2. Snabbknapp & Genvägar",
            "step2_desc": "Koppla SongFlip-genvägen till din snabbknapp för 1-klicks konvertering.",
            "step3_title": "3. Automatiskt urklipp",
            "step3_desc": "Kopierade musiklänkar identifieras automatiskt när appen öppnas.",
            "recent_songs": "SENASTE LÅTAR",
            "show_all": "Visa alla",
            "clipboard_pasted": "Länk klistrades in från urklipp!",
            "clipboard_detected": "Länk upptäcktes i urklipp!",
            "history_empty_title": "Ingen historik än",
            "unknown_song": "Okänd låt"
        ],
        "nl": [
            "app_name": "SongFlip",
            "app_tagline": "Automatische muzieklink-omleiding",
            "target_service_label": "Voorkeurs-doelspeler",
            "nav_settings": "Instellingen",
            "select_language_title": "Selecteer taal",
            "language_label": "Taal",
            "theme_label": "Thema",
            "theme_dark": "Donker",
            "theme_light": "Licht",
            "theme_system": "Systeem",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Plak muzieklink (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Link omzetten",
            "test_converting": "Omzetten via Odesli API...",
            "link_copied": "Link gekopieerd naar klembord",
            "action_paste": "Plakken vanaf klembord",
            "history_title": "Nummergeschiedenis",
            "history_empty": "Nog geen geconverteerde nummers. Gedeelde muzieklinks verschijnen hier.",
            "history_clear_all": "Geschiedenis wissen",
            "history_clear_confirm_title": "Geschiedenis wissen?",
            "action_delete": "Verwijderen",
            "legal_privacy": "Privacy",
            "legal_imprint": "Colofon",
            "legal_terms": "Gebruiksvoorwaarden",
            "redirect_error_toast": "Kon link niet omleiden. Oorspronkelijke link wordt geopend.",
            "section_general": "ALGEMEEN",
            "btn_done": "Gereed",
            "btn_close": "Sluiten",
            "btn_cancel": "Annuleren",
            "auto_clipboard": "Klembord automatisch scannen",
            "one_tap_selection": "1-Tik selectie",
            "how_it_works_ios": "HOE WERKT HET OP IOS?",
            "step1_title": "1. Via Deelmenu",
            "step1_desc": "Tik op Delen in Spotify, Apple Music of YouTube ➔ SongFlip om direct af te spelen.",
            "step2_title": "2. Actieknop & Opdrachten",
            "step2_desc": "Koppel de SongFlip-opdracht aan je actieknop voor conversie met 1 tik.",
            "step3_title": "3. Automatisch klembord",
            "step3_desc": "Gekopieerde muzieklinks worden direct herkend bij het openen van de app.",
            "recent_songs": "RECENTE NUMMERS",
            "show_all": "Alles tonen",
            "clipboard_pasted": "Link geplakt van klembord!",
            "clipboard_detected": "Link gevonden op klembord!",
            "history_empty_title": "Nog geen geschiedenis",
            "unknown_song": "Onbekend nummer"
        ],
        "fr": [
            "app_name": "SongFlip",
            "app_tagline": "Redirection automatique de liens musicaux",
            "target_service_label": "Lecteur cible préféré",
            "nav_settings": "Paramètres",
            "select_language_title": "Choisir la langue",
            "language_label": "Langue",
            "theme_label": "Thème",
            "theme_dark": "Sombre",
            "theme_light": "Clair",
            "theme_system": "Système",
            "nav_test_studio": "Studio de test",
            "test_placeholder": "Collez un lien musical (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convertir le lien",
            "test_converting": "Résolution via l'API Odesli...",
            "link_copied": "Lien copié dans le presse-papiers",
            "action_paste": "Coller depuis le presse-papiers",
            "history_title": "Historique des morceaux",
            "history_empty": "Aucun morceau converti. Les liens partagés apparaîtront ici.",
            "history_clear_all": "Effacer l'historique",
            "history_clear_confirm_title": "Effacer l'historique ?",
            "action_delete": "Supprimer",
            "legal_privacy": "Confidentialité",
            "legal_imprint": "Mentions légales",
            "legal_terms": "\"Conditions d'utilisation\"",
            "redirect_error_toast": "Impossible de rediriger le lien. Ouverture du lien d'origine.",
            "section_general": "GÉNÉRAL",
            "btn_done": "Terminé",
            "btn_close": "Fermer",
            "btn_cancel": "Annuler",
            "auto_clipboard": "Détection auto du presse-papiers",
            "one_tap_selection": "Sélection en 1 geste",
            "how_it_works_ios": "COMMENT ÇA MARCHE SUR IOS ?",
            "step1_title": "1. Via le menu Partager",
            "step1_desc": "Touchez Partager dans Spotify, Apple Music ou YouTube ➔ SongFlip pour lancer la lecture.",
            "step2_title": "2. Bouton d'action & Raccourcis",
            "step2_desc": "Attribuez le raccourci SongFlip à votre bouton d'action pour une conversion en 1 clic.",
            "step3_title": "3. Presse-papiers automatique",
            "step3_desc": "Les liens musicaux copiés sont automatiquement détectés à l'ouverture de l'app.",
            "recent_songs": "MORCEAUX RÉCENTS",
            "show_all": "Tout afficher",
            "clipboard_pasted": "Lien collé depuis le presse-papiers !",
            "clipboard_detected": "Lien détecté dans le presse-papiers !",
            "history_empty_title": "Aucun historique",
            "unknown_song": "Morceau inconnu"
        ],
        "es": [
            "app_name": "SongFlip",
            "app_tagline": "Redirección automática de enlaces de música",
            "target_service_label": "Reproductor de destino preferido",
            "nav_settings": "Ajustes",
            "select_language_title": "Seleccionar idioma",
            "language_label": "Idioma",
            "theme_label": "Tema",
            "theme_dark": "Oscuro",
            "theme_light": "Claro",
            "theme_system": "Sistema",
            "nav_test_studio": "Estudio de prueba",
            "test_placeholder": "Pega un enlace de música (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Convertir enlace",
            "test_converting": "Resolviendo mediante la API de Odesli...",
            "link_copied": "Enlace copiado al portapapeles",
            "action_paste": "Pegar desde el portapapeles",
            "history_title": "Historial de canciones",
            "history_empty": "Aún no hay canciones convertidas. Los enlaces compartidos aparecerán aquí.",
            "history_clear_all": "Borrar historial",
            "history_clear_confirm_title": "¿Borrar historial?",
            "action_delete": "Eliminar",
            "legal_privacy": "Privacidad",
            "legal_imprint": "Aviso legal",
            "legal_terms": "Términos de servicio",
            "redirect_error_toast": "No se pudo redirigir el enlace. Abriendo enlace original.",
            "section_general": "GENERAL",
            "btn_done": "Listo",
            "btn_close": "Cerrar",
            "btn_cancel": "Cancelar",
            "auto_clipboard": "Escanear portapapeles automáticamente",
            "one_tap_selection": "Selección en 1 toque",
            "how_it_works_ios": "¿CÓMO FUNCIONA EN IOS?",
            "step1_title": "1. A través del menú Compartir",
            "step1_desc": "Toca Compartir en Spotify, Apple Music o YouTube ➔ SongFlip para reproducir al instante.",
            "step2_title": "2. Botón de acción y Atajos",
            "step2_desc": "Asigna el atajo de SongFlip al botón de acción para convertir con 1 toque.",
            "step3_title": "3. Portapapeles automático",
            "step3_desc": "Los enlaces de música copiados se detectan automáticamente al abrir la app.",
            "recent_songs": "CANCIONES RECIENTES",
            "show_all": "Ver todo",
            "clipboard_pasted": "¡Enlace pegado del portapapeles!",
            "clipboard_detected": "¡Enlace detectado en el portapapeles!",
            "history_empty_title": "Sin historial aún",
            "unknown_song": "Canción desconocida"
        ],
        "it": [
            "app_name": "SongFlip",
            "app_tagline": "Reindirizzamento automatico dei link musicali",
            "target_service_label": "Lettore di destinazione preferito",
            "nav_settings": "Impostazioni",
            "select_language_title": "Seleziona lingua",
            "language_label": "Lingua",
            "theme_label": "Tema",
            "theme_dark": "Scuro",
            "theme_light": "Chiaro",
            "theme_system": "Sistema",
            "nav_test_studio": "Test Studio",
            "test_placeholder": "Incolla link musicale (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Converti link",
            "test_converting": "Risoluzione tramite API Odesli...",
            "link_copied": "Link copiato negli appunti",
            "action_paste": "Incolla dagli appunti",
            "history_title": "Cronologia brani",
            "history_empty": "Nessun brano convertito. I link musicali condivisi appariranno qui.",
            "history_clear_all": "Cancella cronologia",
            "history_clear_confirm_title": "Cancellare la cronologia?",
            "action_delete": "Elimina",
            "legal_privacy": "Privacy",
            "legal_imprint": "Informazioni legali",
            "legal_terms": "Termini di servizio",
            "redirect_error_toast": "Impossibile reindirizzare il link. Apertura del link originale.",
            "section_general": "GENERALE",
            "btn_done": "Fine",
            "btn_close": "Chiudi",
            "btn_cancel": "Annulla",
            "auto_clipboard": "Rileva automaticamente appunti",
            "one_tap_selection": "Selezione rapida",
            "how_it_works_ios": "COME FUNZIONA SU IOS?",
            "step1_title": "1. Tramite menu Condividi",
            "step1_desc": "Tocca Condividi su Spotify, Apple Music o YouTube ➔ SongFlip per ascoltare subito.",
            "step2_title": "2. Tasto Azione & Comandi",
            "step2_desc": "Assegna il comando SongFlip al tasto Azione per convertire con 1 tocco.",
            "step3_title": "3. Appunti automatici",
            "step3_desc": "I link musicali copiati vengono rilevati automaticamente all'apertura dell'app.",
            "recent_songs": "BRANI RECENTI",
            "show_all": "Mostra tutti",
            "clipboard_pasted": "Link incollato dagli appunti!",
            "clipboard_detected": "Link rilevato negli appunti!",
            "history_empty_title": "Nessuna cronologia",
            "unknown_song": "Brano sconosciuto"
        ],
        "pt": [
            "app_name": "SongFlip",
            "app_tagline": "Redirecionamento automático de links de música",
            "target_service_label": "Reprodutor de destino preferido",
            "nav_settings": "Configurações",
            "select_language_title": "Selecionar idioma",
            "language_label": "Idioma",
            "theme_label": "Tema",
            "theme_dark": "Escuro",
            "theme_light": "Claro",
            "theme_system": "Sistema",
            "nav_test_studio": "Estúdio de Teste",
            "test_placeholder": "Cole o link de música (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Converter link",
            "test_converting": "A resolver via API Odesli...",
            "link_copied": "Link copiado para a área de transferência",
            "action_paste": "Colar da área de transferência",
            "history_title": "Histórico de Músicas",
            "history_empty": "Nenhuma música convertida ainda. Links de música compartilhados aparecerão aqui.",
            "history_clear_all": "Limpar Histórico",
            "history_clear_confirm_title": "Limpar histórico de músicas?",
            "action_delete": "Excluir",
            "legal_privacy": "Privacidade",
            "legal_imprint": "Aviso legal",
            "legal_terms": "Termos de serviço",
            "redirect_error_toast": "Não foi possível redirecionar o link. A abrir link original.",
            "section_general": "GERAL",
            "btn_done": "OK",
            "btn_close": "Fechar",
            "btn_cancel": "Cancelar",
            "auto_clipboard": "Detectar área de transferência automaticamente",
            "one_tap_selection": "Seleção com 1 toque",
            "how_it_works_ios": "COMO FUNCIONA NO IOS?",
            "step1_title": "1. Pelo menu Compartilhar",
            "step1_desc": "Toque em Compartilhar no Spotify, Apple Music ou YouTube ➔ SongFlip para abrir direto.",
            "step2_title": "2. Botão de Ação & Atalhos",
            "step2_desc": "Vincule o atalho do SongFlip ao Botão de Ação para converter em 1 clique.",
            "step3_title": "3. Área de transferência automática",
            "step3_desc": "Links de música copiados são detectados automaticamente ao abrir o app.",
            "recent_songs": "MÚSICAS RECENTES",
            "show_all": "Ver tudo",
            "clipboard_pasted": "Link colado da área de transferência!",
            "clipboard_detected": "Link detectado na área de transferência!",
            "history_empty_title": "Nenhum histórico",
            "unknown_song": "Música desconhecida"
        ],
        "pl": [
            "app_name": "SongFlip",
            "app_tagline": "Automatyczne przekierowywanie linków muzycznych",
            "target_service_label": "Preferowany odtwarzacz docelowy",
            "nav_settings": "Ustawienia",
            "select_language_title": "Wybierz język",
            "language_label": "Język",
            "theme_label": "Motyw",
            "theme_dark": "Ciemny",
            "theme_light": "Jasny",
            "theme_system": "System",
            "nav_test_studio": "Studio testowe",
            "test_placeholder": "Wklej link muzyczny (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konwertuj link",
            "test_converting": "Rozwiązywanie przez Odesli API...",
            "link_copied": "Link skopiowany do schowka",
            "action_paste": "Wklej ze schowka",
            "history_title": "Historia utworów",
            "history_empty": "Brak przekonwertowanych utworów. Udostępnione linki pojawią się tutaj.",
            "history_clear_all": "Wyczyść historię",
            "history_clear_confirm_title": "Wyczyścić historię?",
            "action_delete": "Usuń",
            "legal_privacy": "Prywatność",
            "legal_imprint": "Nota prawna",
            "legal_terms": "Regulamin",
            "redirect_error_toast": "Nie udało się przekierować linku. Otwieranie oryginalnego linku.",
            "section_general": "OGÓLNE",
            "btn_done": "Gotowe",
            "btn_close": "Zamknij",
            "btn_cancel": "Anuluj",
            "auto_clipboard": "Automatycznie sprawdzaj schowek",
            "one_tap_selection": "Wybór 1 dotknięciem",
            "how_it_works_ios": "JAK TO DZIAŁA NA IOS?",
            "step1_title": "1. Przez menu Udostępnij",
            "step1_desc": "Dotknij Udostępnij w Spotify, Apple Music lub YouTube ➔ SongFlip, aby od razu odtworzyć.",
            "step2_title": "2. Przycisk czynności i Skróty",
            "step2_desc": "Przypisz skrót SongFlip do przycisku czynności, aby konwertować jednym kliknięciem.",
            "step3_title": "3. Automatyczny schowek",
            "step3_desc": "Skopiowane linki muzyczne są automatycznie wykrywane po otwarciu aplikacji.",
            "recent_songs": "OSTATNIE UTWORY",
            "show_all": "Pokaż wszystko",
            "clipboard_pasted": "Link wklejony ze schowka!",
            "clipboard_detected": "Wykryto link w schowku!",
            "history_empty_title": "Brak historii",
            "unknown_song": "Nieznany utwór"
        ],
        "ru": [
            "app_name": "SongFlip",
            "app_tagline": "Автоматическая переадресация музыкальных ссылок",
            "target_service_label": "Предпочитаемый плеер",
            "nav_settings": "Настройки",
            "select_language_title": "Выберите язык",
            "language_label": "Язык",
            "theme_label": "Тема",
            "theme_dark": "Тёмная",
            "theme_light": "Светлая",
            "theme_system": "Система",
            "nav_test_studio": "Тестовая студия",
            "test_placeholder": "Вставьте ссылку (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Преобразовать ссылку",
            "test_converting": "Обработка через Odesli API...",
            "link_copied": "Ссылка скопирована в буфер обмена",
            "action_paste": "Вставить из буфера",
            "history_title": "История треков",
            "history_empty": "Пока нет сконвертированных треков. Ссылки появятся здесь.",
            "history_clear_all": "Очистить историю",
            "history_clear_confirm_title": "Очистить историю треков?",
            "action_delete": "Удалить",
            "legal_privacy": "Конфиденциальность",
            "legal_imprint": "Выходные данные",
            "legal_terms": "Условия использования",
            "redirect_error_toast": "Не удалось перенаправить ссылку. Открываем оригинал.",
            "section_general": "ОБЩИЕ",
            "btn_done": "Готово",
            "btn_close": "Закрыть",
            "btn_cancel": "Отмена",
            "auto_clipboard": "Автосканирование буфера обмена",
            "one_tap_selection": "Выбор в 1 касание",
            "how_it_works_ios": "КАК ЭТО РАБОТАЕТ НА IOS?",
            "step1_title": "1. Через меню «Поделиться»",
            "step1_desc": "Нажмите «Поделиться» в Spotify, Apple Music или YouTube ➔ SongFlip для мгновенного перехода.",
            "step2_title": "2. Кнопка действия и Команды",
            "step2_desc": "Назначьте быструю команду SongFlip на кнопку действия для конвертации в 1 клик.",
            "step3_title": "3. Автоматический буфер обмена",
            "step3_desc": "Скопированные музыкальные ссылки автоматически распознаются при открытии приложения.",
            "recent_songs": "НЕДАВНИЕ ТРЕКИ",
            "show_all": "Показать все",
            "clipboard_pasted": "Ссылка вставлена из буфера!",
            "clipboard_detected": "Ссылка обнаружена в буфере обмена!",
            "history_empty_title": "История пуста",
            "unknown_song": "Неизвестный трек"
        ],
        "tr": [
            "app_name": "SongFlip",
            "app_tagline": "Otomatik Müzik Bağlantısı Yönlendirici",
            "target_service_label": "Tercih Edilen Hedef Oynatıcı",
            "nav_settings": "Ayarlar",
            "select_language_title": "Dil Seçin",
            "language_label": "Dil",
            "theme_label": "Tema",
            "theme_dark": "Koyu",
            "theme_light": "Açık",
            "theme_system": "Sistem",
            "nav_test_studio": "Test Stüdyosu",
            "test_placeholder": "Müzik bağlantısını yapıştırın (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Bağlantıyı Dönüştür",
            "test_converting": "Odesli API ile çözülüyor...",
            "link_copied": "Bağlantı panoya kopyalandı",
            "action_paste": "Panodan Yapıştır",
            "history_title": "Şarkı Geçmişi",
            "history_empty": "Henüz dönüştürülmüş şarkı yok. Paylaşılan müzik bağlantıları burada görünecektir.",
            "history_clear_all": "Geçmişi Temizle",
            "history_clear_confirm_title": "Şarkı geçmişi temizlensin mi?",
            "action_delete": "Sil",
            "legal_privacy": "Gizlilik",
            "legal_imprint": "Künye",
            "legal_terms": "Hizmet Şartları",
            "redirect_error_toast": "Bağlantı yönlendirilemedi. Orijinal bağlantı açılıyor.",
            "section_general": "GENEL",
            "btn_done": "Bitti",
            "btn_close": "Kapat",
            "btn_cancel": "Vazgeç",
            "auto_clipboard": "Panoyu otomatik tara",
            "one_tap_selection": "Tek Dokunuşla Seçim",
            "how_it_works_ios": "IOS'TA NASIL ÇALIŞIR?",
            "step1_title": "1. Paylaş Menüsü ile",
            "step1_desc": "Spotify, Apple Music veya YouTube'da Paylaş ➔ SongFlip'e dokunarak anında oynatın.",
            "step2_title": "2. Eylem Düğmesi & Kestirmeler",
            "step2_desc": "Tek tıkla dönüştürme için SongFlip Kestirmesini Eylem Düğmesine atayın.",
            "step3_title": "3. Otomatik Pano",
            "step3_desc": "Kopyalanan müzik bağlantıları uygulama açıldığında otomatik olarak algılanır.",
            "recent_songs": "SON ŞARKILAR",
            "show_all": "Tümünü göster",
            "clipboard_pasted": "Bağlantı panodan yapıştırıldı!",
            "clipboard_detected": "Panoda bağlantı algılandı!",
            "history_empty_title": "Henüz geçmiş yok",
            "unknown_song": "Bilinmeyen Şarkı"
        ],
        "uk": [
            "app_name": "SongFlip",
            "app_tagline": "Автоматична переадресація музичних посилань",
            "target_service_label": "Бажаний цільовий плеєр",
            "nav_settings": "Налаштування",
            "select_language_title": "Оберіть мову",
            "language_label": "Мова",
            "theme_label": "Тема",
            "theme_dark": "Темна",
            "theme_light": "Світла",
            "theme_system": "Система",
            "nav_test_studio": "Тестова студія",
            "test_placeholder": "Вставте посилання (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Перетворити посилання",
            "test_converting": "Обробка через Odesli API...",
            "link_copied": "Посилання скопійовано в буфер обміну",
            "action_paste": "Вставити з буфера",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Конфіденційність",
            "legal_imprint": "Вихідні дані",
            "legal_terms": "Умови використання",
            "redirect_error_toast": "Не вдалося перенаправити посилання. Відкриваємо оригінал.",
            "section_general": "ЗАГАЛЬНІ",
            "btn_done": "Готово",
            "btn_close": "Закрити",
            "btn_cancel": "Скасувати",
            "auto_clipboard": "Автоматично зчитувати буфер обміну",
            "one_tap_selection": "Вибір в 1 дотик",
            "how_it_works_ios": "ЯК ЦЕ ПРАЦЮЄ НА IOS?",
            "step1_title": "1. Через меню «Поділитися»",
            "step1_desc": "Натисніть «Поділитися» в Spotify, Apple Music або YouTube ➔ SongFlip для миттєвого відкриття.",
            "step2_title": "2. Кнопка дії та Швидкі команди",
            "step2_desc": "Призначте команду SongFlip на кнопку дії для конвертації в 1 клік.",
            "step3_title": "3. Автоматичний буфер обміну",
            "step3_desc": "Скопійовані музичні посилання автоматично розпізнаються під час відкриття програми.",
            "recent_songs": "НЕЩОДАВНІ ТРЕКИ",
            "show_all": "Показати всі",
            "clipboard_pasted": "Посилання вставлено з буфера!",
            "clipboard_detected": "Посилання виявлено в буфері обміну!",
            "history_empty_title": "Історія порожня",
            "unknown_song": "Невідомий трек"
        ],
        "ja": [
            "app_name": "SongFlip",
            "app_tagline": "音楽リンク自動リダイレクター",
            "target_service_label": "優先ターゲットプレーヤー",
            "nav_settings": "設定",
            "select_language_title": "言語を選択",
            "language_label": "言語",
            "theme_label": "テーマ",
            "theme_dark": "ダーク",
            "theme_light": "ライト",
            "theme_system": "システム",
            "nav_test_studio": "テストスタジオ",
            "test_placeholder": "音楽リンクを貼り付け (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "リンクを変換",
            "test_converting": "Odesli API で解決中...",
            "link_copied": "クリップボードにコピーしました",
            "action_paste": "クリップボードから貼り付け",
            "history_title": "楽曲履歴",
            "history_empty": "変換された楽曲はまだありません。共有されたリンクがここに表示されます。",
            "history_clear_all": "履歴を消去",
            "history_clear_confirm_title": "楽曲履歴を消去しますか？",
            "action_delete": "削除",
            "legal_privacy": "プライバシー",
            "legal_imprint": "法的情報",
            "legal_terms": "利用規約",
            "redirect_error_toast": "リンクをリダイレクトできませんでした。元のリンクを開きます。",
            "section_general": "一般",
            "btn_done": "完了",
            "btn_close": "閉じる",
            "btn_cancel": "キャンセル",
            "auto_clipboard": "クリップボードを自動検出",
            "one_tap_selection": "ワンタップ選択",
            "how_it_works_ios": "IOSでの使い方",
            "step1_title": "1. 共有メニューから",
            "step1_desc": "Spotify、Apple Music、YouTubeで「共有」➔「SongFlip」をタップして瞬時に再生。",
            "step2_title": "2. アクションボタンとショートカット",
            "step2_desc": "アクションボタンにSongFlipショートカットを割り当てれば、1クリックで変換可能。",
            "step3_title": "3. クリップボード自動検出",
            "step3_desc": "アプリを開くとコピーした音楽リンクを自動で認識します。",
            "recent_songs": "最近の曲",
            "show_all": "すべて表示",
            "clipboard_pasted": "クリップボードからリンクを貼り付けました！",
            "clipboard_detected": "クリップボードのリンクを検出しました！",
            "history_empty_title": "履歴がありません",
            "unknown_song": "不明な曲"
        ],
        "ko": [
            "app_name": "SongFlip",
            "app_tagline": "음악 링크 자동 리디렉터",
            "target_service_label": "선호하는 대상 플레이어",
            "nav_settings": "설정",
            "select_language_title": "언어 선택",
            "language_label": "언어",
            "theme_label": "테마",
            "theme_dark": "다크",
            "theme_light": "라이트",
            "theme_system": "시스템",
            "nav_test_studio": "테스트 스튜디오",
            "test_placeholder": "음악 링크 붙여넣기 (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "링크 변환",
            "test_converting": "Odesli API를 통해 확인 중...",
            "link_copied": "클립보드에 링크가 복사되었습니다",
            "action_paste": "클립보드에서 붙여넣기",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "개인정보처리방침",
            "legal_imprint": "법적 고지",
            "legal_terms": "이용약관",
            "redirect_error_toast": "링크를 리디렉션할 수 없습니다. 원본 링크를 엽니다.",
            "section_general": "일반",
            "btn_done": "완료",
            "btn_close": "닫기",
            "btn_cancel": "취소",
            "auto_clipboard": "클립보드 자동 감지",
            "one_tap_selection": "원터치 선택",
            "how_it_works_ios": "IOS에서 어떻게 동작하나요?",
            "step1_title": "1. 공유 메뉴 이용",
            "step1_desc": "Spotify, Apple Music, YouTube에서 공유 ➔ SongFlip을 누르면 즉시 재생됩니다.",
            "step2_title": "2. 동작 버튼 및 단축어",
            "step2_desc": "동작 버튼에 SongFlip 단축어를 지정하여 원클릭으로 변환하세요.",
            "step3_title": "3. 자동 클립보드 인식",
            "step3_desc": "앱을 열면 복사된 음악 링크가 자동으로 감지됩니다.",
            "recent_songs": "최근 재생 곡",
            "show_all": "모두 보기",
            "clipboard_pasted": "클립보드에서 링크를 붙여넣었습니다!",
            "clipboard_detected": "클립보드 링크가 감지되었습니다!",
            "history_empty_title": "기록이 없습니다",
            "unknown_song": "알 수 없는 곡"
        ],
        "zh": [
            "app_name": "SongFlip",
            "app_tagline": "音乐链接自动重定向器",
            "target_service_label": "首选目标播放器",
            "nav_settings": "设置",
            "select_language_title": "选择语言",
            "language_label": "语言",
            "theme_label": "主题",
            "theme_dark": "深色",
            "theme_light": "浅色",
            "theme_system": "系统",
            "nav_test_studio": "测试工作室",
            "test_placeholder": "粘贴音乐链接 (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "转换链接",
            "test_converting": "通过 Odesli API 解析中...",
            "link_copied": "链接已复制到剪贴板",
            "action_paste": "从剪贴板粘贴",
            "history_title": "歌曲历史",
            "history_empty": "暂无转换记录。分享的音乐链接将显示在这里。",
            "history_clear_all": "清除历史记录",
            "history_clear_confirm_title": "确定清除歌曲历史？",
            "action_delete": "删除",
            "legal_privacy": "隐私政策",
            "legal_imprint": "版本说明",
            "legal_terms": "服务条款",
            "redirect_error_toast": "无法重定向链接。正在打开原始链接。",
            "section_general": "通用",
            "btn_done": "完成",
            "btn_close": "关闭",
            "btn_cancel": "取消",
            "auto_clipboard": "自动读取剪贴板",
            "one_tap_selection": "一键选择",
            "how_it_works_ios": "在 IOS 上如何使用？",
            "step1_title": "1. 通过分享菜单",
            "step1_desc": "在 Spotify、Apple Music 或 YouTube 中点击分享 ➔ 选择 SongFlip 即可立即跳转播放。",
            "step2_title": "2. 操作按钮与快捷指令",
            "step2_desc": "将 SongFlip 快捷指令绑定到操作按钮，即可实现一键转换。",
            "step3_title": "3. 自动读取剪贴板",
            "step3_desc": "打开应用时会自动识别并转换剪贴板中的音乐链接。",
            "recent_songs": "最近转换",
            "show_all": "查看全部",
            "clipboard_pasted": "已从剪贴板粘贴链接！",
            "clipboard_detected": "已识别剪贴板中的链接！",
            "history_empty_title": "暂无记录",
            "unknown_song": "未知歌曲"
        ],
        "in": [
            "app_name": "SongFlip",
            "app_tagline": "Pengalihan Tautan Musik Otomatis",
            "target_service_label": "Pemutar Tujuan Favorit",
            "nav_settings": "Pengaturan",
            "select_language_title": "Pilih Bahasa",
            "language_label": "Bahasa",
            "theme_label": "Tema",
            "theme_dark": "Gelap",
            "theme_light": "Terang",
            "theme_system": "Sistem",
            "nav_test_studio": "Studio Uji",
            "test_placeholder": "Tempel tautan musik (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Konversi Tautan",
            "test_converting": "Menyelesaikan melalui Odesli API...",
            "link_copied": "Tautan disalin ke papan klip",
            "action_paste": "Tempel dari Papan Klip",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Privasi",
            "legal_imprint": "Impresum",
            "legal_terms": "Ketentuan Layanan",
            "redirect_error_toast": "Gagal mengalihkan tautan. Membuka tautan asli.",
            "section_general": "UMUM",
            "btn_done": "Selesai",
            "btn_close": "Tutup",
            "btn_cancel": "Batal",
            "auto_clipboard": "Deteksi papan klip otomatis",
            "one_tap_selection": "Pilihan 1 Ketukan",
            "how_it_works_ios": "BAGAIMANA CARA KERJANYA DI IOS?",
            "step1_title": "1. Melalui Menu Bagikan",
            "step1_desc": "Ketuk Bagikan di Spotify, Apple Music, atau YouTube ➔ SongFlip untuk memutar langsung.",
            "step2_title": "2. Tombol Tindakan & Pintasan",
            "step2_desc": "Tetapkan Pintasan SongFlip ke Tombol Tindakan untuk konversi 1 klik.",
            "step3_title": "3. Papan Klip Otomatis",
            "step3_desc": "Tautan musik yang disalin akan terdeteksi otomatis saat membuka aplikasi.",
            "recent_songs": "LAGU TERBARU",
            "show_all": "Tampilkan semua",
            "clipboard_pasted": "Tautan ditempel dari papan klip!",
            "clipboard_detected": "Tautan terdeteksi di papan klip!",
            "history_empty_title": "Belum ada riwayat",
            "unknown_song": "Lagu Tidak Dikenal"
        ],
        "vi": [
            "app_name": "SongFlip",
            "app_tagline": "Tự động chuyển hướng liên kết âm nhạc",
            "target_service_label": "Trình phát mục tiêu ưa thích",
            "nav_settings": "Cài đặt",
            "select_language_title": "Chọn ngôn ngữ",
            "language_label": "Ngôn ngữ",
            "theme_label": "Giao diện",
            "theme_dark": "Tối",
            "theme_light": "Sáng",
            "theme_system": "Hệ thống",
            "nav_test_studio": "Phòng thử nghiệm",
            "test_placeholder": "Dán liên kết âm nhạc (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "Chuyển đổi liên kết",
            "test_converting": "Đang phân giải qua Odesli API...",
            "link_copied": "Đã sao chép liên kết vào khay nhớ tạm",
            "action_paste": "Dán từ khay nhớ tạm",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "Bảo mật",
            "legal_imprint": "Thông tin pháp lý",
            "legal_terms": "Điều khoản dịch vụ",
            "redirect_error_toast": "Không thể chuyển hướng liên kết. Đang mở liên kết gốc.",
            "section_general": "CHUNG",
            "btn_done": "Xong",
            "btn_close": "Đóng",
            "btn_cancel": "Hủy",
            "auto_clipboard": "Tự động quét khay nhớ tạm",
            "one_tap_selection": "Chọn 1 chạm",
            "how_it_works_ios": "HOẠT ĐỘNG TRÊN IOS NHƯ THẾ NÀO?",
            "step1_title": "1. Qua menu Chia sẻ",
            "step1_desc": "Nhấn Chia sẻ trong Spotify, Apple Music hoặc YouTube ➔ SongFlip để phát ngay lập tức.",
            "step2_title": "2. Nút Tác vụ & Phím tắt",
            "step2_desc": "Gán Phím tắt SongFlip vào Nút Tác vụ để chuyển đổi chỉ với 1 lần chạm.",
            "step3_title": "3. Khay nhớ tạm tự động",
            "step3_desc": "Liên kết nhạc đã sao chép sẽ tự động được nhận diện khi mở ứng dụng.",
            "recent_songs": "BÀI HÁT GẦN ĐÂY",
            "show_all": "Xem tất cả",
            "clipboard_pasted": "Đã dán liên kết từ khay nhớ tạm!",
            "clipboard_detected": "Đã phát hiện liên kết trong khay nhớ tạm!",
            "history_empty_title": "Chưa có lịch sử",
            "unknown_song": "Bài hát không xác định"
        ],
        "bn": [
            "app_name": "SongFlip",
            "app_tagline": "স্বয়ংক্রিয় মিউজিক লিঙ্ক রিডাইরেক্টর",
            "target_service_label": "পছন্দের লক্ষ্য প্লেয়ার",
            "nav_settings": "সেটিংস",
            "select_language_title": "ভাষা নির্বাচন করুন",
            "language_label": "ভাষা",
            "theme_label": "থিম",
            "theme_dark": "গাঢ়",
            "theme_light": "হালকা",
            "theme_system": "সিস্টেম",
            "nav_test_studio": "টেস্ট স্টুডিও",
            "test_placeholder": "মিউজিক লিঙ্ক পেস্ট করুন (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "লিঙ্ক রূপান্তর করুন",
            "test_converting": "Odesli API এর মাধ্যমে সমাধান করা হচ্ছে...",
            "link_copied": "লিঙ্ক ক্লিপবোর্ডে কপি করা হয়েছে",
            "action_paste": "ক্লিপবোর্ড থেকে পেস্ট করুন",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "গোপনীয়তা",
            "legal_imprint": "আইনি বিজ্ঞপ্তি",
            "legal_terms": "পরিষেবার শর্তাবলী",
            "redirect_error_toast": "লিঙ্ক রিডাইরেক্ট করা যায়নি। আসল লিঙ্ক খোলা হচ্ছে।",
            "section_general": "সাধারণ",
            "btn_done": "সম্পন্ন",
            "btn_close": "বন্ধ করুন",
            "btn_cancel": "বাতিল",
            "auto_clipboard": "স্বয়ংক্রিয় ক্লিপবোর্ড স্ক্যান",
            "one_tap_selection": "১-ট্যাপ নির্বাচন",
            "how_it_works_ios": "IOS-এ এটি কীভাবে কাজ করে?",
            "step1_title": "১. শেয়ার মেনুর মাধ্যমে",
            "step1_desc": "Spotify, Apple Music বা YouTube-এ শেয়ার ➔ SongFlip চাপলে সরাসরি প্লে হবে।",
            "step2_title": "২. অ্যাকশন বাটন ও শর্টকাট",
            "step2_desc": "১-ক্লিক কনভার্ট করার জন্য অ্যাকশন বাটনে SongFlip শর্টকাট সেট করুন।",
            "step3_title": "৩. স্বয়ংক্রিয় ক্লিপবোর্ড",
            "step3_desc": "অ্যাপ খুললেই কপি করা মিউজিক লিঙ্ক স্বয়ংক্রিয়ভাবে শনাক্ত হবে।",
            "recent_songs": "সাম্প্রতিক গান",
            "show_all": "সবগুলো দেখুন",
            "clipboard_pasted": "ক্লিপবোর্ড থেকে লিঙ্ক পেস্ট করা হয়েছে!",
            "clipboard_detected": "ক্লিপবোর্ডে লিঙ্ক পাওয়া গেছে!",
            "history_empty_title": "কোনো ইতিহাস নেই",
            "unknown_song": "অজানা গান"
        ],
        "hi": [
            "app_name": "SongFlip",
            "app_tagline": "स्वचालित संगीत लिंक रीडायरेक्टर",
            "target_service_label": "पसंदीदा लक्ष्य प्लेयर",
            "nav_settings": "सेटिंग्स",
            "select_language_title": "भाषा चुनें",
            "language_label": "भाषा",
            "theme_label": "थीम",
            "theme_dark": "डार्क",
            "theme_light": "लाइट",
            "theme_system": "सिस्टम",
            "nav_test_studio": "टेस्ट स्टूडियो",
            "test_placeholder": "संगीत लिंक पेस्ट करें (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "लिंक बदलें",
            "test_converting": "Odesli API के माध्यम से समाधान हो रहा है...",
            "link_copied": "लिंक क्लिपबोर्ड पर कॉपी किया गया",
            "action_paste": "क्लिपबोर्ड से पेस्ट करें",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "गोपनीयता",
            "legal_imprint": "कानूनी नोटिस",
            "legal_terms": "सेवा की शर्तें",
            "redirect_error_toast": "लिंक रीडायरेक्ट नहीं किया जा सका। मूल लिंक खोला जा रहा है।",
            "section_general": "सामान्य",
            "btn_done": "पूर्ण",
            "btn_close": "बंद करें",
            "btn_cancel": "रद्द करें",
            "auto_clipboard": "क्लिपबोर्ड स्वचालित रूप से स्कैन करें",
            "one_tap_selection": "1-टैप चयन",
            "how_it_works_ios": "IOS पर यह कैसे काम करता है?",
            "step1_title": "1. शेयर मेनू के माध्यम से",
            "step1_desc": "Spotify, Apple Music या YouTube में शेयर ➔ SongFlip पर टैप करके तुरंत चलाएं।",
            "step2_title": "2. एक्शन बटन और शॉर्टकट",
            "step2_desc": "1-क्लिक रूपांतरण के लिए SongFlip शॉर्टकट को अपने एक्शन बटन पर सेट करें।",
            "step3_title": "3. स्वचालित क्लिपबोर्ड",
            "step3_desc": "ऐप खोलते ही कॉपी किए गए संगीत लिंक अपने आप पहचान लिए जाते हैं।",
            "recent_songs": "हाल के गाने",
            "show_all": "सभी देखें",
            "clipboard_pasted": "क्लिपबोर्ड से लिंक चिपकाया गया!",
            "clipboard_detected": "क्लिपबोर्ड में लिंक मिला!",
            "history_empty_title": "कोई इतिहास नहीं",
            "unknown_song": "अज्ञात गाना"
        ],
        "mr": [
            "app_name": "SongFlip",
            "app_tagline": "स्वयंचलित संगीत लिंक पुनर्निर्देशन",
            "target_service_label": "पसंतीचा टार्गेट प्लेअर",
            "nav_settings": "सेटिंग्ज",
            "select_language_title": "भाषा निवडा",
            "language_label": "भाषा",
            "theme_label": "थीम",
            "theme_dark": "डार्क",
            "theme_light": "लाइट",
            "theme_system": "सिस्टम",
            "nav_test_studio": "चाचणी स्टुडिओ",
            "test_placeholder": "संगीत लिंक पेस्ट करा (Spotify, Apple, YT Music, Tidal...)",
            "test_button": "लिंक बदला",
            "test_converting": "Odesli API द्वारे शोधत आहे...",
            "link_copied": "लिंक क्लिपबोर्डवर कॉपी केली",
            "action_paste": "क्लिपबोर्डवरून पेस्ट करा",
            "history_title": "Song History",
            "history_empty": "No converted songs yet. Flipped music links will appear here automatically.",
            "history_clear_all": "Clear History",
            "history_clear_confirm_title": "Clear Song History?",
            "action_delete": "Delete",
            "legal_privacy": "गोपनीयता",
            "legal_imprint": "कायदेशीर सूचना",
            "legal_terms": "सेवा अटी",
            "redirect_error_toast": "लिंक पुनर्निर्देशित करता आली नाही. मूळ लिंक उघडत आहे.",
            "section_general": "सामान्य",
            "btn_done": "झाले",
            "btn_close": "बंद करा",
            "btn_cancel": "रद्द करा",
            "auto_clipboard": "क्लिपबोर्ड आपोआप स्कॅन करा",
            "one_tap_selection": "१-टॅप निवड",
            "how_it_works_ios": "IOS वर हे कसे कार्य करते?",
            "step1_title": "१. शेअर मेनूद्वारे",
            "step1_desc": "Spotify, Apple Music किंवा YouTube मध्ये शेअर ➔ SongFlip टॅप करून थेट ऐका.",
            "step2_title": "२. अ‍ॅक्शन बटण व शॉर्टकट",
            "step2_desc": "१-क्लिक रूपांतरणासाठी SongFlip शॉर्टकट अ‍ॅक्शन बटणावर सेट करा.",
            "step3_title": "३. स्वयंचलित क्लिपबोर्ड",
            "step3_desc": "अ‍ॅप उघडताच कॉपी केलेल्या संगीत लिंक्स आपोआप ओळखल्या जातात.",
            "recent_songs": "अलीकडील गाणी",
            "show_all": "सर्व पहा",
            "clipboard_pasted": "क्लिपबोर्डवरून लिंक पेस्ट केली!",
            "clipboard_detected": "क्लिपबोर्डमध्ये लिंक आढळली!",
            "history_empty_title": "अद्याप इतिहास नाही",
            "unknown_song": "अज्ञात गाणे"
        ]
    ]

    static func string(for key: String, lang: String) -> String {
        if let dict = translations[lang], let val = dict[key] {
            return val
        }
        if let enDict = translations["en"], let val = enDict[key] {
            return val
        }
        return key
    }
}

extension View {
    func localized(_ key: String, lang: String) -> String {
        LocalizationManager.string(for: key, lang: lang)
    }
}
